### ISSUE TITLE
No Magic library was found on your system

### ISSUE THREAD

**Issue by AregGhazaryan** [DainisGorbunovs/DeStringCare#3]
Hi i am using both windows and WSL on my pc, and whenever i try to run destringcare it prints bunch of `No Magic library was found on your system` and outputs nothing. Python version on windows 10 is 3.7, on my WSL its 3.8. Am i missing something?

**Comment by AregGhazaryan** [comment]
I managed to fix the issue by installing requirements, but now it shows this error 

```
Traceback (most recent call last):
  File "c:\users\areg\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\areg\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Areg\AppData\Local\Programs\Python\Python37\Scripts\destringcare.exe\__main__.py", line 7, in <module>
  File "c:\users\areg\appdata\local\programs\python\python37\lib\site-packages\DeStringCare\destringcare.py", line 161, in main
    sha1hash = get_key_from_android_debug_keystore(keystore_path)
  File "c:\users\areg\appdata\local\programs\python\python37\lib\site-packages\DeStringCare\destringcare.py", line 154, in get_key_from_android_debug_keystore
    ks = jks.KeyStore.load(keystore_path, keystore_pass)
  File "c:\users\areg\appdata\local\programs\python\python37\lib\site-packages\jks\util.py", line 92, in load
    try_decrypt_keys=try_decrypt_keys)
  File "c:\users\areg\appdata\local\programs\python\python37\lib\site-packages\jks\jks.py", line 490, in loads
    raise BadKeystoreFormatException('Not a JKS or JCEKS keystore'
jks.util.BadKeystoreFormatException: Not a JKS or JCEKS keystore (magic number wrong; expected FEEDFEED or CECECECE)
```
